"""add canonical turn event ledger

Revision ID: 014b33300438
Revises: 724564649a13
Create Date: 2026-07-24 09:07:57.543785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '014b33300438'
down_revision: Union[str, Sequence[str], None] = '724564649a13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_turn_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('turn_id', sa.String(length=36), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.String(length=16), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('payload_digest', sa.String(length=64), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("event_type in ('turn.accepted', 'route.selected', 'retrieval.started', 'retrieval.completed', 'evidence.delta', 'answer.delta', 'turn.completed', 'turn.failed', 'turn.cancelled', 'turn.redacted')", name='ck_conversation_turn_events_type'),
    sa.CheckConstraint("schema_version = '1.0'", name='ck_conversation_turn_events_schema_version'),
    sa.CheckConstraint('length(payload_digest) = 64', name='ck_conversation_turn_events_digest_size'),
    sa.CheckConstraint('sequence >= 1', name='ck_conversation_turn_events_sequence_positive'),
    sa.ForeignKeyConstraint(['turn_id'], ['conversation_turns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_conversation_turn_events_sequence', 'conversation_turn_events', ['turn_id', 'sequence'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_conversation_turn_events_sequence', table_name='conversation_turn_events')
    op.drop_table('conversation_turn_events')
    # ### end Alembic commands ###
