"""baseline phase one schema

Revision ID: 724564649a13
Revises: 
Create Date: 2026-07-24 09:05:44.113479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '724564649a13'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("state in ('approved', 'disabled')", name='ck_prompt_templates_state'),
    sa.CheckConstraint('length(body) > 0 and length(body) <= 2000', name='ck_prompt_templates_body_size'),
    sa.CheckConstraint('length(trim(name)) > 0', name='ck_prompt_templates_name_not_blank'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_prompt_templates_name', 'prompt_templates', ['name'], unique=True)
    op.create_table('provider_configs',
    sa.Column('provider_kind', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('requires_credentials', sa.Boolean(), nullable=False),
    sa.Column('credential_ciphertext', sa.Text(), nullable=True),
    sa.Column('credential_updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("provider_kind in ('openai', 'bedrock', 'ollama', 'reducto')", name='ck_provider_configs_provider_kind'),
    sa.PrimaryKeyConstraint('provider_kind')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_disabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('password_changed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_name', sa.String(length=80), nullable=False),
    sa.Column('actor_kind', sa.String(length=32), nullable=False),
    sa.Column('actor_user_id', sa.String(length=36), nullable=True),
    sa.Column('target_kind', sa.String(length=40), nullable=True),
    sa.Column('target_id', sa.String(length=128), nullable=True),
    sa.Column('request_id', sa.String(length=80), nullable=True),
    sa.Column('trace_id', sa.String(length=80), nullable=True),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('safe_error_code', sa.String(length=64), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("actor_kind in ('public', 'member', 'administrator', 'worker', 'system')", name='ck_audit_events_actor_kind'),
    sa.CheckConstraint("event_name in ('runtime_settings.provider_config_rotated', 'runtime_settings.model_profile_created', 'runtime_settings.model_profile_updated', 'runtime_settings.model_profile_deleted', 'runtime_settings.defaults_updated', 'domain.created', 'domain.started', 'domain.stopped', 'domain.delete_queued', 'domain.delete_succeeded', 'domain.delete_failed', 'source.uploaded', 'source.preparation_retried', 'source.preparation_cancelled', 'source.deleted', 'source.index_retry_queued', 'source.index_cancelled', 'chat.turn_redacted', 'security.admin_route_denied', 'user.disabled', 'user.enabled')", name='ck_audit_events_event_name'),
    sa.CheckConstraint("outcome in ('succeeded', 'failed', 'denied')", name='ck_audit_events_outcome'),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_events_request_id', 'audit_events', ['request_id'], unique=False)
    op.create_index('ix_audit_events_trace_id', 'audit_events', ['trace_id'], unique=False)
    op.create_index('ix_audit_events_created_at', 'audit_events', [sa.text('created_at DESC')], unique=False)
    op.create_index('ix_audit_events_event_created', 'audit_events', ['event_name', sa.text('created_at DESC')], unique=False)
    op.create_index('ix_audit_events_actor_created', 'audit_events', ['actor_user_id', sa.text('created_at DESC')], unique=False)
    op.create_index('ix_audit_events_target_created', 'audit_events', ['target_kind', 'target_id', sa.text('created_at DESC')], unique=False)
    op.create_table('auth_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_sessions_expires_at'), 'auth_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_auth_sessions_token_hash'), 'auth_sessions', ['token_hash'], unique=True)
    op.create_index(op.f('ix_auth_sessions_user_id'), 'auth_sessions', ['user_id'], unique=False)
    op.create_table('composer_ref_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('owner_user_id', sa.String(length=36), nullable=False),
    sa.Column('ref_kind', sa.String(length=16), nullable=False),
    sa.Column('target_id', sa.String(length=64), nullable=False),
    sa.Column('domain_id', sa.String(length=64), nullable=True),
    sa.Column('safe_label', sa.String(length=255), nullable=True),
    sa.Column('safe_description', sa.String(length=500), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("ref_kind in ('source', 'evidence', 'template')", name='ck_composer_ref_tokens_kind'),
    sa.CheckConstraint('length(token_hash) = 64', name='ck_composer_ref_tokens_hash_size'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_composer_ref_tokens_owner_expires', 'composer_ref_tokens', ['owner_user_id', 'expires_at'], unique=False)
    op.create_index('ix_composer_ref_tokens_target', 'composer_ref_tokens', ['ref_kind', 'target_id'], unique=False)
    op.create_index('uq_composer_ref_tokens_hash', 'composer_ref_tokens', ['token_hash'], unique=True)
    op.create_table('conversations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conversations_owner_updated', 'conversations', ['owner_user_id', sa.text('updated_at DESC')], unique=False)
    op.create_table('model_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('profile_kind', sa.String(length=32), nullable=False),
    sa.Column('provider_kind', sa.String(length=32), nullable=False),
    sa.Column('model_name', sa.String(length=200), nullable=False),
    sa.Column('vector_dimensions', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("profile_kind != 'embedding' or vector_dimensions is not null", name='ck_model_profiles_embedding_dimensions_required'),
    sa.CheckConstraint("profile_kind != 'synthesis' or vector_dimensions is null", name='ck_model_profiles_synthesis_dimensions_absent'),
    sa.CheckConstraint("profile_kind in ('synthesis', 'embedding')", name='ck_model_profiles_profile_kind'),
    sa.CheckConstraint("provider_kind in ('openai', 'bedrock', 'ollama')", name='ck_model_profiles_provider_kind'),
    sa.CheckConstraint('vector_dimensions is null or vector_dimensions > 0', name='ck_model_profiles_vector_dimensions_positive'),
    sa.ForeignKeyConstraint(['provider_kind'], ['provider_configs.provider_kind'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_profiles_provider_kind'), 'model_profiles', ['provider_kind'], unique=False)
    op.create_table('conversation_turns',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('client_request_id', sa.String(length=80), nullable=False),
    sa.Column('trace_id', sa.String(length=80), nullable=True),
    sa.Column('domain_id', sa.String(length=64), nullable=True),
    sa.Column('route', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('stop_reason', sa.String(length=32), nullable=True),
    sa.Column('user_message', sa.Text(), nullable=False),
    sa.Column('assistant_answer', sa.Text(), nullable=True),
    sa.Column('safe_error_code', sa.String(length=64), nullable=True),
    sa.Column('safe_error_message', sa.String(length=500), nullable=True),
    sa.Column('composer_ref_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('plan_step_count', sa.Integer(), nullable=False),
    sa.Column('retrieval_operation_count', sa.Integer(), nullable=False),
    sa.Column('repair_attempt_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("(route = 'domain_rag' and domain_id is not null) or (route = 'direct_llm' and domain_id is null)", name='ck_conversation_turns_route_domain'),
    sa.CheckConstraint("route in ('direct_llm', 'domain_rag')", name='ck_conversation_turns_route'),
    sa.CheckConstraint("status in ('running', 'completed', 'failed', 'redacted')", name='ck_conversation_turns_status'),
    sa.CheckConstraint("stop_reason is null or stop_reason in ('direct_llm', 'grounded', 'no_grounded_context', 'evidence_only', 'turn_budget_exhausted', 'provider_failure', 'citation_validation_failed', 'cancelled', 'redacted')", name='ck_conversation_turns_stop_reason'),
    sa.CheckConstraint('plan_step_count >= 0', name='ck_conversation_turns_plan_step_count_nonnegative'),
    sa.CheckConstraint('repair_attempt_count >= 0', name='ck_conversation_turns_repair_attempt_count_nonnegative'),
    sa.CheckConstraint('retrieval_operation_count >= 0', name='ck_conversation_turns_retrieval_operation_count_nonnegative'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_turns_domain_id'), 'conversation_turns', ['domain_id'], unique=False)
    op.create_index(op.f('ix_conversation_turns_trace_id'), 'conversation_turns', ['trace_id'], unique=False)
    op.create_index('uq_conversation_turns_client_request', 'conversation_turns', ['conversation_id', 'client_request_id'], unique=True)
    op.create_index('uq_conversation_turns_one_running', 'conversation_turns', ['conversation_id'], unique=True, sqlite_where=sa.text("status = 'running'"), postgresql_where=sa.text("status = 'running'"))
    op.create_index('ix_conversation_turns_conversation_created', 'conversation_turns', ['conversation_id', sa.text('created_at DESC')], unique=False)
    op.create_table('domains',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('embedding_profile_id', sa.String(length=36), nullable=False),
    sa.Column('runtime_instance_id', sa.String(length=36), nullable=False),
    sa.Column('control_generation', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("state in ('stopped', 'running', 'deleting')", name='ck_domains_state'),
    sa.CheckConstraint('control_generation >= 1', name='ck_domains_control_generation_positive'),
    sa.ForeignKeyConstraint(['embedding_profile_id'], ['model_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domains_embedding_profile_id'), 'domains', ['embedding_profile_id'], unique=False)
    op.create_table('runtime_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active_synthesis_profile_id', sa.String(length=36), nullable=True),
    sa.Column('active_parser_kind', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("active_parser_kind in ('docling', 'reducto')", name='ck_runtime_settings_active_parser_kind'),
    sa.CheckConstraint('id = 1', name='ck_runtime_settings_singleton'),
    sa.ForeignKeyConstraint(['active_synthesis_profile_id'], ['model_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversation_turn_composer_refs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('turn_id', sa.String(length=36), nullable=False),
    sa.Column('ref_order', sa.Integer(), nullable=False),
    sa.Column('ref_kind', sa.String(length=16), nullable=False),
    sa.Column('safe_label', sa.String(length=255), nullable=True),
    sa.Column('safe_description', sa.String(length=500), nullable=True),
    sa.Column('domain_id', sa.String(length=64), nullable=True),
    sa.Column('source_document_id', sa.String(length=36), nullable=True),
    sa.Column('source_block_id', sa.String(length=36), nullable=True),
    sa.Column('evidence_ref_id', sa.String(length=36), nullable=True),
    sa.Column('prompt_template_id', sa.String(length=36), nullable=True),
    sa.Column('redacted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("(ref_kind = 'source' AND source_document_id IS NOT NULL AND evidence_ref_id IS NULL AND prompt_template_id IS NULL) OR (ref_kind = 'evidence' AND evidence_ref_id IS NOT NULL AND source_document_id IS NULL AND source_block_id IS NULL AND prompt_template_id IS NULL) OR (ref_kind = 'template' AND prompt_template_id IS NOT NULL AND source_document_id IS NULL AND source_block_id IS NULL AND evidence_ref_id IS NULL)", name='ck_conversation_turn_composer_refs_kind_target'),
    sa.CheckConstraint("ref_kind in ('source', 'evidence', 'template')", name='ck_conversation_turn_composer_refs_kind'),
    sa.CheckConstraint('(redacted_at IS NULL) OR (safe_label IS NULL AND safe_description IS NULL)', name='ck_conversation_turn_composer_refs_redacted_fields'),
    sa.CheckConstraint('ref_order >= 1', name='ck_conversation_turn_composer_refs_order_positive'),
    sa.ForeignKeyConstraint(['turn_id'], ['conversation_turns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conversation_turn_composer_refs_evidence_ref', 'conversation_turn_composer_refs', ['evidence_ref_id'], unique=False)
    op.create_index('ix_conversation_turn_composer_refs_source_document', 'conversation_turn_composer_refs', ['source_document_id'], unique=False)
    op.create_index('ix_conversation_turn_composer_refs_template', 'conversation_turn_composer_refs', ['prompt_template_id'], unique=False)
    op.create_index('ix_conversation_turn_composer_refs_turn_kind', 'conversation_turn_composer_refs', ['turn_id', 'ref_kind'], unique=False)
    op.create_index('uq_conversation_turn_composer_refs_order', 'conversation_turn_composer_refs', ['turn_id', 'ref_order'], unique=True)
    op.create_table('conversation_turn_evidence_refs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('turn_id', sa.String(length=36), nullable=False),
    sa.Column('evidence_order', sa.Integer(), nullable=False),
    sa.Column('source_document_id', sa.String(length=36), nullable=False),
    sa.Column('source_block_id', sa.String(length=36), nullable=False),
    sa.Column('citation_label', sa.String(length=16), nullable=True),
    sa.Column('source_label', sa.String(length=255), nullable=True),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('redacted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('(redacted_at IS NULL) OR (citation_label IS NULL AND source_label IS NULL AND excerpt IS NULL)', name='ck_conversation_turn_evidence_refs_redacted_fields'),
    sa.CheckConstraint('evidence_order >= 1', name='ck_conversation_turn_evidence_refs_order_positive'),
    sa.ForeignKeyConstraint(['turn_id'], ['conversation_turns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conversation_turn_evidence_refs_source_document', 'conversation_turn_evidence_refs', ['source_document_id'], unique=False)
    op.create_index('uq_conversation_turn_evidence_refs_citation_label', 'conversation_turn_evidence_refs', ['turn_id', 'citation_label'], unique=True, sqlite_where=sa.text('redacted_at IS NULL'), postgresql_where=sa.text('redacted_at IS NULL'))
    op.create_index('uq_conversation_turn_evidence_refs_order', 'conversation_turn_evidence_refs', ['turn_id', 'evidence_order'], unique=True)
    op.create_table('domain_operations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('domain_id', sa.String(length=64), nullable=False),
    sa.Column('operation_type', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('control_generation_at_start', sa.Integer(), nullable=False),
    sa.Column('requested_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('request_id', sa.String(length=80), nullable=True),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('lease_owner', sa.String(length=64), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("operation_type in ('create', 'start', 'stop', 'delete')", name='ck_domain_operations_type'),
    sa.CheckConstraint("status in ('queued', 'running', 'succeeded', 'failed', 'cancelled')", name='ck_domain_operations_status'),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domain_operations_request_id'), 'domain_operations', ['request_id'], unique=False)
    op.create_index('uq_domain_operations_one_active', 'domain_operations', ['domain_id'], unique=True, sqlite_where=sa.text("status IN ('queued', 'running')"), postgresql_where=sa.text("status IN ('queued', 'running')"))
    op.create_index('ix_domain_operations_domain_created', 'domain_operations', ['domain_id', sa.text('created_at DESC')], unique=False)
    op.create_table('source_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('domain_id', sa.String(length=64), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=160), nullable=False),
    sa.Column('original_sha256', sa.String(length=64), nullable=False),
    sa.Column('original_size_bytes', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('parser_kind', sa.String(length=32), nullable=False),
    sa.Column('preparation_generation', sa.Integer(), nullable=False),
    sa.Column('index_state', sa.String(length=16), nullable=False),
    sa.Column('index_generation', sa.Integer(), nullable=False),
    sa.Column('index_request_id', sa.String(length=96), nullable=True),
    sa.Column('index_content_hash', sa.String(length=64), nullable=True),
    sa.Column('index_remote_document_id', sa.String(length=128), nullable=True),
    sa.Column('index_error_code', sa.String(length=64), nullable=True),
    sa.Column('index_error_message', sa.String(length=500), nullable=True),
    sa.Column('index_lease_owner', sa.String(length=64), nullable=True),
    sa.Column('index_lease_expires_at', sa.DateTime(), nullable=True),
    sa.Column('index_accepted_at', sa.DateTime(), nullable=True),
    sa.Column('index_ready_at', sa.DateTime(), nullable=True),
    sa.Column('index_updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("index_state in ('not_requested', 'queued', 'submitting', 'accepted', 'ready', 'failed', 'cancelling', 'cancelled')", name='ck_source_documents_index_state'),
    sa.CheckConstraint("parser_kind in ('docling', 'reducto')", name='ck_source_documents_parser_kind'),
    sa.CheckConstraint("state in ('pending', 'prepared', 'deleting')", name='ck_source_documents_state'),
    sa.CheckConstraint('index_generation >= 0', name='ck_source_documents_index_generation_nonnegative'),
    sa.CheckConstraint('original_size_bytes > 0', name='ck_source_documents_size_positive'),
    sa.CheckConstraint('preparation_generation >= 1', name='ck_source_documents_generation_positive'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_source_documents_domain_index_state', 'source_documents', ['domain_id', 'index_state'], unique=False)
    op.create_index('uq_source_documents_domain_hash', 'source_documents', ['domain_id', 'original_sha256'], unique=True)
    op.create_index('ix_source_documents_domain_created', 'source_documents', ['domain_id', sa.text('created_at DESC')], unique=False)
    op.create_table('source_blocks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_document_id', sa.String(length=36), nullable=False),
    sa.Column('domain_id', sa.String(length=64), nullable=False),
    sa.Column('source_order', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('canonical_markdown', sa.Text(), nullable=False),
    sa.Column('heading_level', sa.Integer(), nullable=True),
    sa.Column('page_start', sa.Integer(), nullable=True),
    sa.Column('page_end', sa.Integer(), nullable=True),
    sa.Column('section_path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("kind in ('text', 'table', 'figure')", name='ck_source_blocks_kind'),
    sa.CheckConstraint('heading_level is null or heading_level >= 1', name='ck_source_blocks_heading_positive'),
    sa.CheckConstraint('page_end is null or page_end >= 1', name='ck_source_blocks_page_end_positive'),
    sa.CheckConstraint('page_start is null or page_end is null or page_end >= page_start', name='ck_source_blocks_page_range'),
    sa.CheckConstraint('page_start is null or page_start >= 1', name='ck_source_blocks_page_start_positive'),
    sa.CheckConstraint('source_order >= 1', name='ck_source_blocks_order_positive'),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_source_blocks_domain_source', 'source_blocks', ['domain_id', 'source_document_id'], unique=False)
    op.create_index('uq_source_blocks_source_order', 'source_blocks', ['source_document_id', 'source_order'], unique=True)
    op.create_table('source_preparation_operations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_document_id', sa.String(length=36), nullable=False),
    sa.Column('domain_id', sa.String(length=64), nullable=False),
    sa.Column('operation_type', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('preparation_generation_at_start', sa.Integer(), nullable=False),
    sa.Column('requested_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('request_id', sa.String(length=80), nullable=True),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('lease_owner', sa.String(length=64), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("operation_type in ('prepare')", name='ck_source_preparation_operations_type'),
    sa.CheckConstraint("status in ('queued', 'running', 'succeeded', 'failed', 'cancelled')", name='ck_source_preparation_operations_status'),
    sa.CheckConstraint('preparation_generation_at_start >= 1', name='ck_source_preparation_operations_generation_positive'),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_preparation_operations_request_id'), 'source_preparation_operations', ['request_id'], unique=False)
    op.create_index('uq_source_preparation_operations_one_active', 'source_preparation_operations', ['source_document_id'], unique=True, sqlite_where=sa.text("status IN ('queued', 'running')"), postgresql_where=sa.text("status IN ('queued', 'running')"))
    op.create_index('ix_source_preparation_operations_domain_created', 'source_preparation_operations', ['domain_id', sa.text('created_at DESC')], unique=False)
    op.create_index('ix_source_preparation_operations_source_created', 'source_preparation_operations', ['source_document_id', sa.text('created_at DESC')], unique=False)
    op.create_table('source_images',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_document_id', sa.String(length=36), nullable=False),
    sa.Column('source_block_id', sa.String(length=36), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('mime_type', sa.String(length=80), nullable=False),
    sa.Column('alt_text', sa.String(length=500), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('page_number is null or page_number >= 1', name='ck_source_images_page_positive'),
    sa.ForeignKeyConstraint(['source_block_id'], ['source_blocks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_source_images_source_block', 'source_images', ['source_document_id', 'source_block_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_source_images_source_block', table_name='source_images')
    op.drop_table('source_images')
    op.drop_index('ix_source_preparation_operations_source_created', table_name='source_preparation_operations')
    op.drop_index('ix_source_preparation_operations_domain_created', table_name='source_preparation_operations')
    op.drop_index('uq_source_preparation_operations_one_active', table_name='source_preparation_operations', sqlite_where=sa.text("status IN ('queued', 'running')"), postgresql_where=sa.text("status IN ('queued', 'running')"))
    op.drop_index(op.f('ix_source_preparation_operations_request_id'), table_name='source_preparation_operations')
    op.drop_table('source_preparation_operations')
    op.drop_index('uq_source_blocks_source_order', table_name='source_blocks')
    op.drop_index('ix_source_blocks_domain_source', table_name='source_blocks')
    op.drop_table('source_blocks')
    op.drop_index('ix_source_documents_domain_created', table_name='source_documents')
    op.drop_index('uq_source_documents_domain_hash', table_name='source_documents')
    op.drop_index('ix_source_documents_domain_index_state', table_name='source_documents')
    op.drop_table('source_documents')
    op.drop_index('ix_domain_operations_domain_created', table_name='domain_operations')
    op.drop_index('uq_domain_operations_one_active', table_name='domain_operations', sqlite_where=sa.text("status IN ('queued', 'running')"), postgresql_where=sa.text("status IN ('queued', 'running')"))
    op.drop_index(op.f('ix_domain_operations_request_id'), table_name='domain_operations')
    op.drop_table('domain_operations')
    op.drop_index('uq_conversation_turn_evidence_refs_order', table_name='conversation_turn_evidence_refs')
    op.drop_index('uq_conversation_turn_evidence_refs_citation_label', table_name='conversation_turn_evidence_refs', sqlite_where=sa.text('redacted_at IS NULL'), postgresql_where=sa.text('redacted_at IS NULL'))
    op.drop_index('ix_conversation_turn_evidence_refs_source_document', table_name='conversation_turn_evidence_refs')
    op.drop_table('conversation_turn_evidence_refs')
    op.drop_index('uq_conversation_turn_composer_refs_order', table_name='conversation_turn_composer_refs')
    op.drop_index('ix_conversation_turn_composer_refs_turn_kind', table_name='conversation_turn_composer_refs')
    op.drop_index('ix_conversation_turn_composer_refs_template', table_name='conversation_turn_composer_refs')
    op.drop_index('ix_conversation_turn_composer_refs_source_document', table_name='conversation_turn_composer_refs')
    op.drop_index('ix_conversation_turn_composer_refs_evidence_ref', table_name='conversation_turn_composer_refs')
    op.drop_table('conversation_turn_composer_refs')
    op.drop_table('runtime_settings')
    op.drop_index(op.f('ix_domains_embedding_profile_id'), table_name='domains')
    op.drop_table('domains')
    op.drop_index('ix_conversation_turns_conversation_created', table_name='conversation_turns')
    op.drop_index('uq_conversation_turns_one_running', table_name='conversation_turns', sqlite_where=sa.text("status = 'running'"), postgresql_where=sa.text("status = 'running'"))
    op.drop_index('uq_conversation_turns_client_request', table_name='conversation_turns')
    op.drop_index(op.f('ix_conversation_turns_trace_id'), table_name='conversation_turns')
    op.drop_index(op.f('ix_conversation_turns_domain_id'), table_name='conversation_turns')
    op.drop_table('conversation_turns')
    op.drop_index(op.f('ix_model_profiles_provider_kind'), table_name='model_profiles')
    op.drop_table('model_profiles')
    op.drop_index('ix_conversations_owner_updated', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index('uq_composer_ref_tokens_hash', table_name='composer_ref_tokens')
    op.drop_index('ix_composer_ref_tokens_target', table_name='composer_ref_tokens')
    op.drop_index('ix_composer_ref_tokens_owner_expires', table_name='composer_ref_tokens')
    op.drop_table('composer_ref_tokens')
    op.drop_index(op.f('ix_auth_sessions_user_id'), table_name='auth_sessions')
    op.drop_index(op.f('ix_auth_sessions_token_hash'), table_name='auth_sessions')
    op.drop_index(op.f('ix_auth_sessions_expires_at'), table_name='auth_sessions')
    op.drop_table('auth_sessions')
    op.drop_index('ix_audit_events_target_created', table_name='audit_events')
    op.drop_index('ix_audit_events_actor_created', table_name='audit_events')
    op.drop_index('ix_audit_events_event_created', table_name='audit_events')
    op.drop_index('ix_audit_events_created_at', table_name='audit_events')
    op.drop_index('ix_audit_events_trace_id', table_name='audit_events')
    op.drop_index('ix_audit_events_request_id', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('provider_configs')
    op.drop_index('uq_prompt_templates_name', table_name='prompt_templates')
    op.drop_table('prompt_templates')
    # ### end Alembic commands ###
