from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from fastapi import FastAPI

APP_DIR = Path(__file__).resolve().parents[1] / "app"
sys.path.insert(0, str(APP_DIR))

from context_engine.api.contract_app import (  # noqa: E402
    API_TITLE,
    API_VERSION,
    register_contract_routes,
)


DEFAULT_OUTPUT = APP_DIR / "contracts" / "openapi.json"


def render_openapi() -> bytes:
    app = FastAPI(title=API_TITLE, version=API_VERSION)
    register_contract_routes(app)
    return (json.dumps(app.openapi(), indent=2, sort_keys=True) + "\n").encode()


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate the registered Context Engine OpenAPI document.")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true", help="Fail when output differs from generated bytes.")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    generated = render_openapi()
    output = args.output.resolve()

    if args.check:
        try:
            current = output.read_bytes()
        except OSError:
            current = None
        if current != generated:
            print(f"generated OpenAPI is stale: {output}", file=sys.stderr)
            return 1
        return 0

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_bytes(generated)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
